version: '3'
services:
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: moundir
      MONGO_INITDB_ROOT_PASSWORD: moundir
    volumes:
     - db-data:/data/db
    networks:
     - portfolio-network
volumes:
  db-data: {}
networks:
  portfolio-network:
    driver: bridge